name: Create Release Branch and PR

on:
  push:
    branches:
      - develop

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Calculate Next Version
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch

      - name: Create and Push Release Branch
        id: create_branch
        run: |
          VERSION="${{ steps.version.outputs.new_tag }}"
          BRANCH_NAME="release-$VERSION"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          echo "Vers√£o calculada: $VERSION"
          echo "Criando branch: $BRANCH_NAME"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Create Pull Request to Homol
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.create_branch.outputs.branch_name }}"
          gh pr create \
            --base homol \
            --head $BRANCH_NAME \
            --title "Release Candidate: $BRANCH_NAME to Homol" \
            --body "Automated PR for Homol release created from Develop." \
            || echo "PR creation failed or PR already exists."
